### ISSUE TITLE
pony-zmq does not compile with latest ponyc

### ISSUE THREAD

**Issue by tj800x** [jemc/pony-zmq#3]
I'm having trouble building pony-zmq with pony 0.12.2.   Thanks.  Tom.

Building builtin -> /usr/local/lib/pony/0.12.2-dc26414/packages/builtin
Building zmq/test -> /Users/tjohnson/Projects/Pony/pony-zmq/zmq/test
Error:
/Users/tjohnson/Projects/Pony/pony-zmq/zmq/test/socket_type_tests.pony:184:42: syntax error: unterminated array literal
    recv_unordered_set(h, rs, s, recover [
                                         ^
    Info:
    /Users/tjohnson/Projects/Pony/pony-zmq/zmq/test/socket_type_tests.pony:185:46: expected terminating ] before here
          recover val zmq.Message.>push("a1") end,
                                                 ^
Error:
/Users/tjohnson/Projects/Pony/pony-zmq/zmq/test/socket_type_tests.pony:234:42: syntax error: unterminated array literal
    recv_unordered_set(h, rs, s, recover [
                                         ^
    Info:
    /Users/tjohnson/Projects/Pony/pony-zmq/zmq/test/socket_type_tests.pony:235:56: expected terminating ] before here
          recover val zmq.Message.>push("a").>push("A") end,
                                                           ^
Error:
/Users/tjohnson/Projects/Pony/pony-zmq/zmq/test/z85_test.pony:11:40: syntax error: unterminated array literal
    test_pair(h, "HelloWorld", recover [as U8:
                                       ^
    Info:
    /Users/tjohnson/Projects/Pony/pony-zmq/zmq/test/z85_test.pony:12:11: expected terminating ] before here
          0x86, 0x4F, 0xD2, 0x6F, 0xB5, 0x59, 0xF7, 0x5B

**Comment by jemc** [comment]
Thanks for prodding me about this. The syntax for array literals changed quite recently.

Fixed it with f0496b86718ecce3090c4ced7dcd695f373d0f38.

**Comment by tj800x** [comment]
I appreciate it.  I just found Pony and am wowed!

Seeing other people's code is often a good way to learn.

Thanks,

Tom Johnson

**Comment by jemc** [comment]
No problem!

Feel free to pop into the mailing list or IRC channel if you have any questions.
